version: "3.7"

services:
  spoiler_bot:
    container_name: spoiler_bot
    build: .
    volumes:
      - type: bind
        source: ./env.json
        target: /app/env.json
        read_only: true
      - type: bind
        source: ./latestSpoiler.json
        target: /app/latestSpoiler.json
        read_only: false
      - type: bind
        source: ./comms.json
        target: /app/comms.json
        read_only: false

